const fs = require("fs");
const path = require("path");

// --- CONFIGURATION ---
const weights = ["outline", "bold"];
const baseDir = path.join(__dirname, ".");
const rawDir = path.join(baseDir, "src", "raw");
const outputDir = path.join(baseDir, "src", "generated");

// --- UTILITIES ---

const toPascalCase = (str) => str;

// Helper to extract viewBox and inner HTML from an SVG string
function parseSvg(svgString) {
  // 1. Extract ViewBox
  const viewBoxMatch = svgString.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : "0 0 256 256";

  // 2. Extract Inner Content
  let content = svgString.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");

  // 3. Normalize Attributes

  // A. HANDLE FILL:
  // If a path has fill="none" or fill="#000", remove the fill attribute entirely.
  // This allows the component's 'fill' prop (or Tailwind class) to take control.
  content = content.replace(/\sfill="[^"]*"/g, (match) => {
    // Keep fill="none" as it is critical for outline icons (hollow centers).
    if (match.includes("none")) return match;
    // Remove everything else so it inherits from parent
    return "";
  });

  // B. HANDLE STROKE:
  // Similar logic. If stroke is explicitly set to black, remove it so it inherits.
  content = content.replace(/\sstroke="[^"]*"/g, (match) => {
    if (match.includes("none")) return match;
    return "";
  });

  return { viewBox, content };
}

// --- DYNAMIC DISCOVERY ---
const outlineDir = path.join(rawDir, "outline");

if (!fs.existsSync(outlineDir)) {
  console.error(`❌ Error: Directory not found: ${outlineDir}`);
  console.error("Please create an 'outline' folder in your src/raw directory.");
  process.exit(1);
}

// Discover icon names
const iconNames = fs
  .readdirSync(outlineDir)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.replace(".svg", ""))
  .map((name) => toPascalCase(name));

console.log(`🔍 Discovered ${iconNames.length} icons.`);

// --- BUILD LOGIC ---

if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

let exportStatements = [];

iconNames.forEach((name) => {
  const weightContents = {};
  let sharedViewBox = null;
  let hasAtLeastOneWeight = false;

  weights.forEach((weight) => {
    const possibleFilenames = [`${name}.svg`, `${name.toLowerCase()}.svg`];

    let svgContent = null;
    for (const filename of possibleFilenames) {
      const filePath = path.join(rawDir, weight, filename);
      if (fs.existsSync(filePath)) {
        svgContent = fs.readFileSync(filePath, "utf-8");
        break;
      }
    }

    if (svgContent) {
      const parsed = parseSvg(svgContent);
      weightContents[weight] = parsed.content;
      if (!sharedViewBox) sharedViewBox = parsed.viewBox;
      hasAtLeastOneWeight = true;
    }
  });

  if (!hasAtLeastOneWeight) {
    console.warn(`⚠️  Skipping ${name}: No SVG files found in any weight folder.`);
    return;
  }

  const componentName = name;
  const availableWeightsString = JSON.stringify(Object.keys(weightContents));

  const boldContentString = (weightContents["bold"] || "").replace(/`/g, "\\`");
  const outlineContentString = (weightContents["outline"] || "").replace(/`/g, "\\`");

  const componentTemplate = `import * as React from "react";
import { IconProps } from "./types";

export const ${componentName}: React.FC<IconProps> = ({ size = 24, color = "currentColor", weight = "outline", ...props }) => {
  const availableWeights = ${availableWeightsString};
  const activeWeight = availableWeights.includes(weight) ? weight : availableWeights[0];

  return (
    <svg
      viewBox="${sharedViewBox}"
      width={size}
      height={size}
      fill={color}
      {...props}
    >
      {activeWeight === 'bold' && (
        <g dangerouslySetInnerHTML={{ __html: \`${boldContentString}\` }} />
      )}
      {activeWeight === 'outline' && (
        <g dangerouslySetInnerHTML={{ __html: \`${outlineContentString}\` }} />
      )}
    </svg>
  );
};
`;

  const outputPath = path.join(outputDir, `${componentName}.tsx`);
  fs.writeFileSync(outputPath, componentTemplate);

  exportStatements.push(`export { ${componentName} } from "./${componentName}";`);
});

// --- NEW: COPY TYPES FILE ---
// This ensures the generated folder is self-contained and types.ts is available for the users
const typesSource = path.join(baseDir, "src", "types.ts");
const typesDest = path.join(outputDir, "types.ts");

if (fs.existsSync(typesSource)) {
  fs.copyFileSync(typesSource, typesDest);
  console.log(`📄 Copied types.ts to generated folder.`);
} else {
  console.warn("⚠️  src/types.ts not found! Please create it in your src folder.");
  process.exit(1);
}

// --- GENERATE INDEX ---
const indexTemplate = `// Auto-generated by build.js
import { IconProps } from "./types";

 ${exportStatements.join("\n")}
`;

fs.writeFileSync(path.join(outputDir, "index.ts"), indexTemplate);
console.log(`✅ Build Complete! Generated ${iconNames.length} unified components in src/generated/`);
